image: elixir:latest

before_script:
  - git clone https://github.com/zeionara/tiger.git
  - cd tiger
  - git checkout dev
  - mix deps.get

create-task:
  stage: build
  script:
    - timestamp=$(get_field() { echo $CI_COMMIT_TIMESTAMP | cut -d 'T' -f 1 | cut -d '-' -f $1; }; echo "$(get_field 3)-$(get_field 2)-$(get_field 1)")
    - author=$(echo $CI_COMMIT_AUTHOR | cut -d '<' -f 2 | cut -d '@' -f 1)

    # - echo "Creating task from commit with title '$CI_COMMIT_TITLE' and description '$CI_COMMIT_DESCRIPTION' which was made '$timestamp' by $author"
    # - echo "Credentials key: '$TRELLO_KEY' token: '$TRELLO_TOKEN' board: '$TRELLO_BOARD'"

    - mix run main.exs -b "$TRELLO_BOARD" -l 'done' -m "$author" -d "$CI_COMMIT_DESCRIPTION" -ct "$CI_COMMIT_TITLE" -c "$timestamp" --zoom --done --skip
